version: "3"

services:
  redis:
    image: redis:alpine3.14
    restart: always

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
    restart: always

  flask:
    image: webapp-flask
    build:
      args:
        TARGET: "${FLASK_APP_TARGET}"
        SOURCE: "${FLASK_APP_SOURCE}"
      context: .
      dockerfile: dockerfile-flask
    environment:
      - FLASK_ENV="production"
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
    restart: always
    volumes:
      - "${FLASK_APP_SOURCE}:${FLASK_APP_TARGET}"

  worker:
    image: webapp-flask
    command: celery -A osgs_admin.tasks.celery worker -l INFO
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - flask
    restart: always
    volumes:
      - "${FLASK_APP_SOURCE}:${FLASK_APP_TARGET}"

  watchdog:
    image: webapp-watchdog
    build:
      args:
        TARGET: "${FLASK_APP_TARGET}"
      context: .
      dockerfile: dockerfile-watchdog
    depends_on:
      - flask
    restart: always
    volumes:
      - "${FLASK_APP_SOURCE}:${FLASK_APP_TARGET}"

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: dockerfile-nginx
    ports:
      - ${APP_PUBLIC_PORT}:80
    depends_on:
      - flask
    restart: always
