FROM python:3.8

RUN apt update && apt install -y python3-pip && pip3 install watchdog

ADD ./watcher.py /watcher.py

ARG TARGET
ENV TARGET $TARGET

# Run watchdog script unbuffered to ensure that the stdout and stderr
# are available when running as daemonized process in the container.
# The environment variable does the same thing as the -u switch
# both are included here simply for the sake of redundancy/ resilience.
ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python3","-u","/watcher.py"]
