FROM python:3.8.12-bullseye

ARG TARGET
ARG SOURCE

RUN mkdir "$TARGET"
WORKDIR "$TARGET"

EXPOSE 5000

COPY "$SOURCE" .

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD [ "uwsgi", "--ini", "uwsgi.ini" ]
